### ISSUE TITLE
Plotting Support

### ISSUE THREAD

**Issue by josephhardinee** [josephhardinee/PyDSD#35]
While PyDisdrometer has some basic plotting routines, I plan on going through and adding more before the v1.0 release. Please comment here on any routines in particular you would like to see.

**Comment by nguy** [comment]
I also need to port over some that I used with pyparticleprobe. I'll try to get to that in the next few weeks.

**Comment by nguy** [comment]
PR #48

**Comment by josephhardinee** [comment]
Most of these have now been merged in. Closing this as complete, though the HovMoller plot needs some fixing. I think I may have introduced some unoptimal parts to the plots that I'll open in another issue.
