### ISSUE TITLE
Rain rate support

### ISSUE THREAD

**Issue by bdolan44** [josephhardinee/PyDSD#4]
I'd like to request support for reading in rain rates from NASA GV data (JW and 2DVD).

**Comment by nguy** [comment]
@josephhardinee has this been completed? It looks like there are readers in there for this now.

**Comment by josephhardinee** [comment]
There is a reader for the main formats they put out, the issue is they strip the rain rate information out into a separate file. I need to revisit whether or not that functionality is still needed as we can process some of the base files now.

**Comment by nguy** [comment]
Cool beans.

**Comment by josephhardinee** [comment]
I believe they re-issued new file formats and so I think this is no longer an issue. Feel free to re-open if this is still needed.
