### ISSUE TITLE
Spresd

### ISSUE THREAD

**Issue by yogeshkkolte** [josephhardinee/PyDSD#42]
Hello Sir,
In calculation of DSD  i dont understand the term "spread" , is id difference between two diameter interval? 
 def conv_md_to_nd(self, Nd):
        F = 0.005
        t = 30.0
        v = 9.65 - 10.3 * np.exp(-0.6 * self.diameter)
        return np.divide(Nd, (F * t * np.multiply(v, self.spread)))
can you  explain ?

**Comment by josephhardinee** [comment]
It is the width of each size bin. For uniformly spaced bins it is width between bins, otherwise it varies somewhat.

**Comment by nguy** [comment]
Hmmm, do you think some metadata should be attached (is it currently?)

**Comment by josephhardinee** [comment]
I think there should be, and for some there is. I need to redo a few of these to use the utility object we generated for attaching metadata from a config file.
