### ISSUE TITLE
calculate_dsd_parametrization returns empty 'D0' (all nan)

### ISSUE THREAD

**Issue by dagnachewl** [josephhardinee/PyDSD#65]
Hello josephhardinee,

Thank you for this excellent project. I have some Parsivel data and calculate_dsd_parametrization returns empty (all nan) field for D0 all the time. Is this something known to anyone else? I can send an example data if need be. All the other parameters in ['D0', 'Dmax', 'Dm', 'Nt', 'Nw', 'N0', 'W', 'mu'] seem fine. 

Could it possibly be related to the use of numpy functions like cumsum instead of nancumsum on the masked Nd data?

I get  a"Warning message" that 

UserWarning: Warning: converting a masked element to nan.
  return array(a, dtype, copy=False, order=order)
/home/dagnachew/anaconda3/lib/python3.6/site-packages/pydsd/DropSizeDistribution.py:349: RuntimeWarning: invalid value encountered in less
  cross_pt = list(cum_W < (cum_W[-1] * 0.5)).index(False) - 1

(Pdb) c
/home/dagnachew/anaconda3/lib/python3.6/site-packages/pytmatrix/psd.py:183: RuntimeWarning: invalid value encountered in greater
  psd[(D > self.D_max) | (D==0.0)] = 0.0

On Ubuntu 16. Python 3.6 (Anaconda)

Thanks

**Comment by sysumeteo** [comment]
I  had also encountered this error,i think it maybe a bug related to the 'numpy.nan' and 'np.cum', because when i replace np.nan with 0.0 in 'Nd' , 'D0' can be calculated correctly.

**Comment by josephhardinee** [comment]
Hey sorry, somehow this issue never popped up in my email. I apologize for the huge amount of time it took to get back to this. I'll take a look at this over the weekend. @sysumeteo is correct that we'd always assumed that bins had real values. My gut feeling is that we should infill 0's to make sense of this.

**Comment by josephhardinee** [comment]
Okay I believe this should be fixed by PR #88 . I added a few other sanity checks in there and a few unit tests. Thanks for catching this. I'm going to close this, but if this does not fix your issue, please feel free to re-open it.
