### ISSUE TITLE
calculate_R_Zh_relationship call error

### ISSUE THREAD

**Issue by aamatthews** [josephhardinee/PyDSD#70]
I ran dsd.calculate_R_Zh_relationship() and got the following error: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-322-6a685964115c> in <module>()
----> 1 dsd.calculate_R_Zh_relationship()

/Users/matt493/PyDSD/pydsd/DropSizeDistribution.pyc in calculate_R_Zh_relationship(self)
    439 
    440         popt, pcov = expfit(
--> 441             np.power(10, 0.1 * self.fields["Zh"]["data"][self.rain_rate["data"] > 0]),
    442             self.fields["rain_rate"]["data"][self.fields["rain_rate"]["data"] > 0],
    443         )

TypeError: 'NoneType' object has no attribute '__getitem__'

It seems this is occurring because self.rain_rate doesn't exist. It is now in the "fields", so should be called by: self.fields['rain_rate']['data'] instead.

**Comment by aamatthews** [comment]
I should add, the call to rain_rate is correct in line 442, but not in 441.

**Comment by josephhardinee** [comment]
This is fixed by PR #72. Closing.
