### ISSUE TITLE
Vertical incidance 

### ISSUE THREAD

**Issue by yogeshkkolte** [josephhardinee/PyDSD#83]
I am using radar data in vertical pointing mode so how can i perform scattering simulations in case of vertical incidence ?

Thank you

**Comment by scollis** [comment]
on average all hydrometeors will have zero anisotropy. Vertically pointing nd^6 should be highly valid.. ZDR and KDP = 0

**Comment by yogeshkkolte** [comment]
Can i use
scatterer.psd_integrator.geometries = (tmatrix_aux.geom_vert_back, tmatrix_aux.geom_vert_forw)
instead of
scatterer.psd_integrator.geometries = ( tmatrix_aux.geom_horiz_back, tmatrix_aux.geom_horiz_forw)

**Comment by jleinonen** [comment]
> Can i use
> scatterer.psd_integrator.geometries = (tmatrix_aux.geom_vert_back, tmatrix_aux.geom_vert_forw)
> instead of
> scatterer.psd_integrator.geometries = ( tmatrix_aux.geom_horiz_back, tmatrix_aux.geom_horiz_forw)
> 
> To perform scattering simulation for elevation angle of 90 degree .

Yes, this should work. If you need more fine control over the orientation you can manually set the geometries. See the PyTMatrix [documentation](https://github.com/jleinonen/pytmatrix/wiki#methods).

**Comment by josephhardinee** [comment]
I'm going to set this as closed. If the solution didn't work for you, then feel free to re-open. Thanks @jleinonen for answering it.
